name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Se connecter à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          # username: ${{ secrets.DOCKER_USERNAME }}
          # password: ${{ secrets.DOCKER_PASSWORD }}
          username: bintou34
          password: Bintou2005@

      # Étape 3 : Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t bintou2005@/my-python-app:latest .

      # Étape 4 : Pousser l'image Docker
      - name: Push Docker image
        run: |
          docker push bintou2005@/my-python-app:latest
